### ISSUE TITLE
User should be allowed to progress even if some genes not recognized

### ISSUE THREAD

**Issue by cmungall** [evoldoers/wtfgo#1]
Unrecognized genes may simply mean the genes are valid but unannotated. The user should be warned, but able to progress regardless

my jquery skillz are not up to it, is this the right place to hack?

https://github.com/evoldoers/wtfgo/blob/70372cba76d477e10da730cf74cb74345554e0d4/web/client.js#L420-L440

**Comment by ihh** [comment]
At the moment (awful hack) this code is directly duplicated from wtfgenes. So the actual place to hack is here:
https://github.com/evoldoers/wtfgenes/blob/master/web/client.js#L420-L440

And then the code should be copied across to wtfgo, which is a repo specifically aimed at demo-ing wtfgenes on the GO datasets.

Anyway, I would have to play with it a little but yes I think that is the right place.
